export default {
  COLORS: {
    PRIMARY: '#fe7d55',
    PRIMARY_LIGHT: '#FEA488',
    DARK_TEXT_COLOR: '#1E1E1E',
    LIGHT_TEXT_COLOR: '#A0A0A0',
    BACKGROUND_COLOR: '#f4f4f4',
    WHITE: 'white',
  },
  SIZES: {
    BASE: 16,
    BUBBLE_HEIGHT: 100,
    BUBBLE_WIDTH: 100,
    BUBBLE_BORDER_RADIUS: 30,
    STEP_BUBBLE_SIZE: 24,
    CODE_CONTAINER_HEIGHT: 50,
    CODE_CONTAINER_WIDTH: 200,
    CODE_CONTAINER_BORDER_RADIUS: 8,
  },
};
